### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by getnamo** [uetopia/uetopia-online-subsystem#1]
Can't really use this in other projects without a clear license file, whichever license you choose it should be ideally made clear on the main repository.

At the very least ensure you add the required MIT headers for VARest, socket.io-client-cpp, and Socket.IO Client (https://github.com/getnamo/socketio-client-ue4/blob/master/LICENSE) since this repository contains code from them and the conditions of MIT requires that notice.

**Comment by uetopia** [comment]
Thanks.  Included.
